"""initial-db-tables

Revision ID: d925cb39480e
Revises:
Create Date: 2022-05-05 11:45:18.781171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d925cb39480e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column(
            "contact_id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("author_status", sa.String(), nullable=False),
        sa.Column("endorse_status", sa.String(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column(
            "connection_protocol", sa.String(), nullable=False
        ),
        sa.Column(
            "connection_alias", sa.String(), nullable=True
        ),
        sa.Column("public_did", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("their_label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("contact_id"),
    )
    op.create_table(
        "endorserequest",
        sa.Column(
            "endorse_request_id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("endorser_did", sa.String(), nullable=False),
        sa.Column("author_did", sa.String(), nullable=True),
        sa.Column(
            "transaction_type", sa.String(), nullable=True
        ),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("ledger_txn", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("endorse_request_id"),
    )
    op.create_table(
        "configurationdb",
        sa.Column(
            "config_id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("config_name", sa.String(), nullable=False),
        sa.Column("config_value", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("config_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("endorserequest")
    op.drop_table("contact")
    op.drop_table("configurationdb")
    # ### end Alembic commands ###
