FROM ghcr.io/openwallet-foundation/acapy-agent:py3.12-1.3.2

USER root

RUN pip install git+https://github.com/openwallet-foundation/acapy-plugins@1.3.1#subdirectory=webvh

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
COPY ngrok-wait.sh ngrok-wait.sh
RUN chmod +x ./ngrok-wait.sh

USER $user
